version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
  db:
    image: mysql:5.7
    container_name: base_datos
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_PASSWORD: '1234'
      MYSQL_DATABASE: db_so1
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
