version: '3'
services:
  grpc_server:
    build: ./gRPC/Server
    ports:
      - '50051:50051' 
    networks:
      - my_network
    depends_on:
      - db

  grpc_client:
    build: ./gRPC/Client
    ports:
      - '7070:7070' 
    networks:
      - my_network
    depends_on:
      - grpc_server

  redisservicio:
    image: redis:alpine
    container_name: rediscontenedor
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - my_network

  db:
    image: mysql:5.7
    container_name: base_datos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_PASSWORD: '1234'
      MYSQL_DATABASE: db_so1
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

  redispub:
    build: ./Redispub
    ports:
      - "8082:8082"
    environment:
      TZ: America/Guatemala
    depends_on:
      - redisservicio
    networks:
      - my_network
  
  redissub:
    build: ./Redissub
    environment:
      TZ: America/Guatemala
    depends_on:
      - redisservicio
      - db
    networks:
      - my_network

  api:
    build: ./API
    ports:
      - '8080:8080' 
    networks:
      - my_network
    depends_on:
      - db
      - redisservicio


volumes:
  db_data:

networks:
  my_network: 
    driver: bridge
